// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_X1TYET8vKq82qyKCAoOxtBMUk6zZuyg',
    appId: '1:64937910786:web:f755f52b4f162d19857d1b',
    messagingSenderId: '64937910786',
    projectId: 'prelims-prep-ca',
    authDomain: 'prelims-prep-ca.firebaseapp.com',
    storageBucket: 'prelims-prep-ca.firebasestorage.app',
    measurementId: 'G-2G4J424TLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_qJZQP9AmIOO-A8oXBv199STxtn8_3WI',
    appId: '1:64937910786:android:90122e4e51c27245857d1b',
    messagingSenderId: '64937910786',
    projectId: 'prelims-prep-ca',
    storageBucket: 'prelims-prep-ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3P2Ja4NH-1Rf0gl4lJ-khjqmpKUFeJ_M',
    appId: '1:64937910786:ios:863e5d9ee0f806c0857d1b',
    messagingSenderId: '64937910786',
    projectId: 'prelims-prep-ca',
    storageBucket: 'prelims-prep-ca.firebasestorage.app',
    iosBundleId: 'com.nandu.upscCaUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3P2Ja4NH-1Rf0gl4lJ-khjqmpKUFeJ_M',
    appId: '1:64937910786:ios:863e5d9ee0f806c0857d1b',
    messagingSenderId: '64937910786',
    projectId: 'prelims-prep-ca',
    storageBucket: 'prelims-prep-ca.firebasestorage.app',
    iosBundleId: 'com.nandu.upscCaUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_X1TYET8vKq82qyKCAoOxtBMUk6zZuyg',
    appId: '1:64937910786:web:399d74cb5769d1b8857d1b',
    messagingSenderId: '64937910786',
    projectId: 'prelims-prep-ca',
    authDomain: 'prelims-prep-ca.firebaseapp.com',
    storageBucket: 'prelims-prep-ca.firebasestorage.app',
    measurementId: 'G-Z873P82ECW',
  );
}
